<?php

/**
 * Implements hook_menu().
 */
function synch_users_from_external_database_menu() {
  $items['user/synch'] = array(
    'title' => '',
    'page callback' => 'start_synch_users_from_external_database',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Executing synch.
 */
function start_synch_users_from_external_database() {
  // Write to watch dog
  watchdog ("synch_users_from_external_database","Start synch URL visited");

  // Define queue  
  $queue_for_synch_users = DrupalQueue::get('queue_for_synch_users');
  $queues['$queue_for_synch_users'] = array(
    'worker callback' => 'queue_for_synch_users_process',
    'time' => 10,
  );
  
  // Check elements in queue
  if ($queue_for_synch_users->numberOfItems()) {
    // Write to watch dog
    $number_entries_in_queue = $queue_for_synch_users->numberOfItems();
    watchdog ("synch_users_from_external_database","The queue is not empty and has " . $number_entries_in_queue . " records. Begin executing records...");
  } else
  {
    // Write to watch dog
    watchdog ("synch_users_from_external_database","The queue is empty, start to fill...");
 	
    $users = array(
      array(
        "login" => "user001",
        "fullname" => "fullname001",
        "email" => "user001@user.user",
        "personnel_number" => "001"
      ),
      array(
        "login" => "user002",
        "fullname" => "fullname002",
        "email" => "user002@user.user",
        "personnel_number" => "002"
      ),
      array(
        "login" => "user003",
        "fullname" => "fullname003",
        "email" => "user003@user.user",
        "personnel_number" => "003"
      ),
      array(
        "login" => "user004",
        "fullname" => "fullname004",
        "email" => "user004@user.user",
        "personnel_number" => "004"
      ),
      array(
        "login" => "user005",
        "fullname" => "fullname005",
        "email" => "user005@user.user",
        "personnel_number" => "005"
      )
    );	
	
    foreach ( $users as $user ) {
      $queue_for_synch_users->createItem($user);
	  watchdog("synch_users_from_external_database","Add item to row " . $user['login']);
    }
	$number_entries_in_queue = $queue_for_synch_users->numberOfItems();
  }  
}

function queue_for_synch_users_process() {
  watchdog("synch_users_from_external_database","Execute record in queue");
}
